### PR TITLE
Reenable Scala 2.12, upgrade dependencies

### PR DESCRIPTION
**Pull request by durban**

### CODE REVIEW

**Comment by mpilquist** [comment]
Thanks! Will do a release soon (hopefully this weekend)

**Comment by durban** [comment]
Great, thanks!

**Comment by mpilquist** [comment]
0.3.0 is on Maven Central now. Sorry for the delay -- was going to do this before holidays but it didn't happen. :)

**Comment by durban** [comment]
Thanks, and no worries :-)

**Pull request merged**
